-- MySQL Script generated by MySQL Workbench
-- Tue Nov 24 21:50:55 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema miriadecommerce
-- -----------------------------------------------------
USE `miriadecommerce` ;

-- -----------------------------------------------------
-- Table `miriadecommerce`.`ps_tmp_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miriadecommerce`.`ps_tmp_image` (
  `ps_id` INT NOT NULL,
  `old_path` VARCHAR(1000) NULL,
  `new_path` VARCHAR(1000) NULL,
  `md5_digest` LONGTEXT NULL,
  `color_analysis` LONGTEXT NULL,
  `status` INT NULL,
  `fk_ps_id` INT NOT NULL,
  PRIMARY KEY (`ps_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miriadecommerce`.`ps_buffer_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miriadecommerce`.`ps_buffer_product` (
  `reference` VARCHAR(100) NOT NULL,
  `attivo` INT NULL,
  `categoria` VARCHAR(200) NULL,
  `prezzo` FLOAT NULL,
  `supplier` VARCHAR(45) NULL,
  `manufacture` VARCHAR(45) NULL,
  `qta` FLOAT NULL,
  `qta_min` FLOAT NULL,
  `lunghezza` FLOAT NULL,
  `altezza` FLOAT NULL,
  `larghezza` FLOAT NULL,
  `colore` VARCHAR(45) NULL,
  `quantita` VARCHAR(45) NULL,
  `taglia` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NULL,
  `modello` VARCHAR(45) NULL,
  `linea` VARCHAR(45) NULL,
  `codice_colore` VARCHAR(10) NULL,
  `codice_taglia` VARCHAR(10) NULL,
  `url` VARCHAR(700) NULL,
  `immagine` VARCHAR(700) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miriadecommerce`.`ps_tmp_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miriadecommerce`.`ps_tmp_product` (
  `ps_id` INT NOT NULL,
  `reference` VARCHAR(100) NOT NULL,
  `attivo` INT NULL,
  `categoria` VARCHAR(200) NULL,
  `prezzo` FLOAT NULL,
  `supplier` VARCHAR(45) NULL,
  `manufacture` VARCHAR(45) NULL,
  `qta` FLOAT NULL,
  `qta_min` FLOAT NULL,
  `lunghezza` FLOAT NULL,
  `altezza` FLOAT NULL,
  `larghezza` FLOAT NULL,
  `colore` VARCHAR(45) NULL,
  `quantita` VARCHAR(45) NULL,
  `taglia` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NULL,
  `modello` VARCHAR(45) NULL,
  `linea` VARCHAR(45) NULL,
  `codice_colore` VARCHAR(10) NULL,
  `codice_taglia` VARCHAR(10) NULL,
  `url` VARCHAR(700) NULL,
  `immagine` VARCHAR(700) NULL)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `miriadecommerce`.`brand_mapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miriadecommerce`.`brand_mapping` (
  `sap_brand_name` VARCHAR(200) NOT NULL,
  `ps_brand_name` VARCHAR(200) NOT NULL)
ENGINE = InnoDB;